program: sweep_train.py
method: bayes
metric:
  name: final/val_auc
  goal: maximize
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.001
  reg:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  drop_out:
    values: [0.1, 0.25, 0.5]
  model_type:
    values: [clam_sb, clam_mb]
  model_size:
    values: [small, big]
  bag_weight:
    distribution: uniform
    min: 0.5
    max: 0.9
  B:
    values: [4, 8, 16]
  inst_loss:
    values: [svm, ce]
  patience:
    values: [5, 10, 15]
